apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tileserv.fullname" . }}-secret
  namespace: 
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/tileserv/db/url
    secretKey: DATABASE_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: tileserv-prod-secret
    template:
      metadata: {}
